name: 'Merge Conflict Commenter'
description: 'Automatically post a comment on PRs that have merge conflicts'
author: 'invakid404'
inputs:
  message:
    required: true
    description: 'Message to comment'
    default: 'This PR has merge conflicts!'
runs:
  using: 'node12'
  main: 'dist/index.js'
